### ISSUE TITLE
Questions about find_prompt function

### ISSUE THREAD

**Issue by SmileShaun** [jianzongwu/Language-Driven-Video-Inpainting#3]
Hello, I am a newbie about MLLM and would like to ask you some questions. I am sorry to bother you.

I don't understand the specific function of find_prompt. Is there any difference between <PROMPT> and </PROMPT>?

Why didn't you choose to directly encode the text description generated by llava and then feed it to Inpainting network?

Thank u.

**Comment by jianzongwu** [comment]
We did not directly encode the whole text description generated by llava because the long sentence has many meaningless words for diffusion models, like "I guess you want to....." Sentences like these are not likely to be inputs for the pre-trained diffusion models. So we set a explicit <PROMPT> token to include the "remove ..." expressions in llava's output.

The function "find_prompt" in the paper is to find the prompt included by <PROMPT> and </PROMPT> tokens. It is a simple string match function.
